{
  "comments": [
    {
      "key": {
        "uuid": "1c0fc7ba_4f40d660",
        "filename": "mongo/private/roots/command/errors.go",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1012922
      },
      "writtenOn": "2018-03-05T19:30:40Z",
      "side": 1,
      "message": "What\u0027s the difference between a \"command failure\" and a \"command execution error\"?",
      "revId": "4150271a4e134daf1ba934b828b2f043778951ec",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "11790d4d_b4db71dd",
        "filename": "mongo/private/roots/command/errors.go",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1001503
      },
      "writtenOn": "2018-03-05T19:38:40Z",
      "side": 1,
      "message": "Command failure comes from a query failure whereas a command execution error can be any error from the database.",
      "parentUuid": "1c0fc7ba_4f40d660",
      "revId": "4150271a4e134daf1ba934b828b2f043778951ec",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a05fa509_016096c6",
        "filename": "mongo/private/roots/command/errors.go",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1012922
      },
      "writtenOn": "2018-03-05T20:11:47Z",
      "side": 1,
      "message": "Can you document this? It doesn\u0027t seem obvious from the names.",
      "parentUuid": "11790d4d_b4db71dd",
      "revId": "4150271a4e134daf1ba934b828b2f043778951ec",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "59455fcd_882b43ec",
        "filename": "mongo/private/roots/command/errors.go",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1001503
      },
      "writtenOn": "2018-03-05T20:13:37Z",
      "side": 1,
      "message": "CommandFailure should be called QueryFailure, so I\u0027ll change it to that, since we\u0027ll OP_QUERY will be used for actual queries when we add 3.0 support.",
      "parentUuid": "a05fa509_016096c6",
      "revId": "4150271a4e134daf1ba934b828b2f043778951ec",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "30c57a66_c04c3e47",
        "filename": "mongo/private/roots/command/errors.go",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1012922
      },
      "writtenOn": "2018-03-05T21:24:32Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "59455fcd_882b43ec",
      "revId": "4150271a4e134daf1ba934b828b2f043778951ec",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}